I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 445, in script
    show 1a 2a hola
Exception: Image '1a 2a' does not accept attributes 'hola'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 445, in script
    show 1a 2a hola
  File "C:\Users\Salomón\Documents\Escuela\Narrativa int\Cum\renpy-8.3.7-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Salomón\Documents\Escuela\Narrativa int\Cum\renpy-8.3.7-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Salomón\Documents\Escuela\Narrativa int\Cum\renpy-8.3.7-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Salomón\Documents\Escuela\Narrativa int\Cum\renpy-8.3.7-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Salomón\Documents\Escuela\Narrativa int\Cum\renpy-8.3.7-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\Salomón\Documents\Escuela\Narrativa int\Cum\renpy-8.3.7-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image '1a 2a' does not accept attributes 'hola'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.7.25031702
Date Choice 1 1.0
Wed May 14 05:30:44 2025
